### ISSUE TITLE
Changing only ligand chain

### ISSUE THREAD

**Issue by juliette1996** [nlesc-nano/CAT#255]
Hi Bas,

we have a NC core capped with acetates and we would like to replace these acetates by a series of other carboxylic acids (for example oleic acid) while keeping the anchoring group in the exact same position. In practice instead of having dummy atoms in the input structure we already have ligands for which we would like to change only the alkylic chain.
Is that already feasible in CAT or can you maybe add a function to do it?
Thanks in advance!

**Comment by BvB93** [comment]
Feature currently planned for the 1.1 release later this week.
